version: "3.8"

services:
  obsbox:
    image: ghcr.io/neox5/obsbox:latest
    container_name: otel-testbench-obsbox
    volumes:
      - ./1_simulation/obsbox_ibmmq.yaml:/config/config.yaml:ro
    networks:
      - testbench

  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:latest
    container_name: otel-testbench-otel-collector
    volumes:
      - ./2_collection/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8888:8888" # Metrics endpoint
    networks:
      - testbench

  victoriametrics:
    image: docker.io/victoriametrics/victoria-metrics:latest
    container_name: otel-testbench-victoriametrics
    command:
      - -envflag.enable
      - -envflag.prefix=VM_
    env_file:
      - ./3_datasources/victoriametrics.env
    ports:
      - "8428:8428"
    volumes:
      - victoriametrics-data:/victoria-metrics-data
    networks:
      - testbench

  loki:
    image: docker.io/grafana/loki:latest
    container_name: otel-testbench-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./3_datasources/loki.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - testbench

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: otel-testbench-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./4_grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./4_grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - testbench

networks:
  testbench:
    driver: bridge

volumes:
  victoriametrics-data:
  loki-data:
  grafana-data:
